name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # ou a branch que você usa como principal

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Adicione aqui passos para instalar dependências e rodar testes se necessário
      # Exemplo:
      # - name: Install dependencies
      #   run: npm install
      #
      # - name: Run tests
      #   run: npm test

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ # O diretório a ser publicado, neste caso a raiz do projeto